package main

import (
	"calculator/server/api"
  	"fmt"
	"github.com/gin-gonic/gin"
    _ "calculator/docs"

	"github.com/swaggo/gin-swagger"
    // "github.com/swaggo/gin-swagger/swaggerFiles"
	   swaggerfiles "github.com/swaggo/files"
    // _ "./docs" // The docs is generated by Swag CLI, you have to import it.

)


// @title Swagger Example API
// @version 1.0
// @description This is a sample server for Swagger. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
// @termsOfService http://swagger.io/terms/
// swagger:meta
func main() {
	defaultPort:="8000"
	r := gin.Default()

    // Register the Swagger handler
    r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

    // Your routes go here

    r.Run(":8000")



  fmt.Println("Successfully connected!")

	router := gin.Default()

	// api.Init()

	api.Routes(router)
	router.Run(defaultPort)



}
